# version: '3.8'

services:
  # Service de base de données PostgreSQL
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service de l'application FastAPI
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME=ecommerce_user
      - DB_PASSWORD=ecommerce_password
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_NAME=ecommerce_db
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
